<?php

namespace AppBundle\Repository;

/**
 * ClatesalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClatesalRepository extends \Doctrine\ORM\EntityRepository
{
}
