<?php

namespace AppBundle\Repository;

/**
 * DepartamentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartamentoRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByDivisionId($divisionId)
    {
        $em = $this->getEntityManager();

        $query = "
            SELECT d
                FROM AppBundle:Departamento d
                   
                    JOIN d.division div
                WHERE div.id = :division_id AND d.nombre NOT LIKE 'DIVISION%'
                  
        ";

        $consulta = $em->createQuery($query);
        
        $consulta->setParameter('division_id', $divisionId);

        return $consulta->getResult();
    }

    public function getByDivisionIdArray($divisionId)
    {
        $em = $this->getEntityManager();

        $query = "
            SELECT d
                FROM AppBundle:Departamento d
                    
                    JOIN d.division div
                WHERE  div.id = :division_id AND d.nombre NOT LIKE 'DIVISION%'
        ";

        $consulta = $em->createQuery($query);
        
        $consulta->setParameter('division_id', $divisionId);

        return $consulta->getArrayResult();
    }
}
